### ISSUE TITLE
propType of style should be object instead of number

### ISSUE THREAD

**Issue by blackbing** [huiseoul/react-native-fit-image#20]
https://github.com/huiseoul/react-native-fit-image/blob/master/FitImage.js#L13

**Comment by originerd** [comment]
Hi, @blackbing.

It makes sense to be issued. If you pass the style props directly as object like,

``` javascript
<FitImage
  source={{ uri: 'http://facebook.github.io/react/img/logo_og.png' }}
  style={{ borderRadius: 20 }}
/>
```

propType of style should be object as you mentioned.

But, if you pass the style props via StyleSheet like,

``` javascript
var styles = StyleSheet.create({
  fitImage: {
    borderRadius: 20,
  },
});

<FitImage
  source={{ uri: 'http://facebook.github.io/react/img/logo_og.png' }}
  style={styles.fitImage}
/>
```

it is [transformed into plain number](https://facebook.github.io/react-native/docs/style.html#declare-styles). I prefer to StyleSheet way, so I decided propType of style to be number.

Thanks for reporting.

**Comment by blackbing** [comment]
I see. How about 
`
Image.propTypes.style
`
I think it will be better to follow the original `Image` propTypes rule.

**Comment by originerd** [comment]
@blackbing Yeah, it's a better idea. Thanks 😄 .

I'll update about it.
