### ISSUE TITLE
No gif supported?

### ISSUE THREAD

**Issue by krailler** [huiseoul/react-native-fit-image#39]
Failed to get size for image: *.gif. It is possible in some way?

**Comment by originerd** [comment]
Hi, @krailler.

I checked it. It works for gif image. But it doesn't work for `http` images. Instead if you use `https` for source, you can draw fit image. I don't know why it has changed at this time. I used Image component to get image size, so it's up to Image component of React Native. But I'll check it to solve this problem.

Thanks for reporting.

**Comment by originerd** [comment]
https://github.com/facebook/react-native/issues/8520
