### ISSUE TITLE
setState on unmounted component warning

### ISSUE THREAD

**Issue by sunkibaek** [huiseoul/react-native-fit-image#45]
If you unmount `FitImage` component (i.e. navigate to somewhere else) before finishing to fetch image, following error shows:

```
Warning: setState(...): Can only update a mounted or mounting component. This usually means you called setState() on an unmounted component. This is a no-op. Please check the code for the Image component.
```

I believe following code can cause this kind of warning:

https://github.com/huiseoul/react-native-fit-image/blob/master/src/FitImage.js#L80

Maybe, canceling image loading when the component unmounts will get rid of the warnings -- not sure how to do it, though.

**Comment by johnwook** [comment]
👍

**Comment by originerd** [comment]
Finally, I fixed it. :tada:

https://github.com/huiseoul/react-native-fit-image/releases/tag/v1.4.8
