### ISSUE TITLE
Android image will shake when loading.

### ISSUE THREAD

**Issue by lin493369** [huiseoul/react-native-fit-image#46]
Version:
    "react-native-fit-image": "^1.4.7",
    "react-native": "0.38.0"
Q:
This component is pretty for me.It work well in iOS.
But image will shake （Flashing?） when loading in android device.
Please tell me how to solve this.
@huiseoul

**Comment by originerd** [comment]
Have you tried to reinstall node modules? I don't know it could be a solution for your problem, but I think it deserves to try.

**Comment by hydraZty** [comment]
I have this problem too .
It's likes the picture loading two or three times.

and i haven't type "indicator" in the tag 

I think it's maybe because .load image resource from facebook cdn


Android 
Version:
"react-native-fit-image": "1.4.8",
