### ISSUE TITLE
Loving this component thank you, sometimes it fails to render?

### ISSUE THREAD

**Issue by mattcleary55** [huiseoul/react-native-fit-image#48]
Hey!

Thank you for creating this.

I have a social app in which users can create posts with images in the feed. I've noticed that sometimes the image just fails to render. Any idea why this could be? It's pretty rare, but it's very odd!

Thank you!

**Comment by pckz** [comment]
same here, the image keeps blured :/

thanks anyway, hope you continue the develop of the component

**Comment by pckz** [comment]
hey @judgejab! I solved the problem calculating the sizes using a function built in Image component:
Here is the link http://stackoverflow.com/questions/39497211/react-native-image-height-full-width/42268828#42268828

Code example by @nburk (stackoverflow)

```
class PostItem extends React.Component {

  state = {
    imgWidth: 0,
    imgHeight: 0,
  }

  componentDidMount() {

    Image.getSize(this.props.imageUrl, (width, height) => {
      // calculate image width and height 
      const screenWidth = Dimensions.get('window').width
      const scaleFactor = width / screenWidth
      const imageHeight = height / scaleFactor
      this.setState({imgWidth: screenWidth, imgHeight: imageHeight})
    })
  }

  render() {

    const {imgWidth, imgHeight} = this.state

    return (
      <View>
        <Image
          style={{width: imgWidth, height: imgHeight}}
          source={{uri: this.props.imageUrl}}
        />
        <Text style={styles.title}>
          {this.props.description}
        </Text>
      </View>
    )
  }
}

```

I became like crazy trying to solve this issue, but now works perfectly
