### ISSUE TITLE
Element type is invalid

### ISSUE THREAD

**Issue by bvanleeuwen1995** [huiseoul/react-native-fit-image#57]
Hello,

I just tried to install this plugin, but got a error when trying to use it in my React Native app. The error message is:
'Element type is undefined: excepted a sting (for built-in components) or class/function' (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in.

Check the render method of `Image`.'

Current using:
react-native-cli: 2.0.1
react-native: 0.44.0

**Comment by sunkibaek** [comment]
Would you share what the source code look like when you are using this library?

**Comment by bvanleeuwen1995** [comment]
I'm sorry, completely forgot to include my code:
`import * as React from "react";
import {Text, View, TouchableHighlight} from "react-native";
import FitImage from 'react-native-fit-image';
import mainStyles from "../styles/main.js";

class UserBlock extends React.Component {
    constructor(props) {
        super(props);
    }

    render() {
        // Get the navigate from the parent
        const navigate = this.props.screenProps.navigate;
        const showDetail = this.props.screenProps.showDetail;
        const user = this.props.screenProps.user;
        let detailButton = null;

        if (showDetail !== undefined && showDetail !== null && showDetail === true) {
            detailButton = (
                <TouchableHighlight style={mainStyles.userBlock.detailsButton} onPress={() => {
                    navigate('PlayerProfile', {...user})
                }}>
                    <Text style={mainStyles.userBlock.detailButtonText}>Details</Text>
                </TouchableHighlight>
            );
        }

        return (
            <View style={mainStyles.userBlock.mainView}>
                <View style={mainStyles.userBlock.touchBlock}>
                    <FitImage
                        resizeMode="contain"
                        source={{ uri: user.photoUrl }}
                    />
                    <Text style={{paddingTop: 4}}>{user.name}</Text>
                    <Text>ELO: {user.elo}</Text>
                    {detailButton}
                </View>
            </View>
        );
    }
}

export default UserBlock;`

The strange thing is, when I dismiss the error message it does seem to work, however it just keeps reloading the image.

**Comment by bvanleeuwen1995** [comment]
The reloading has been fixed  with remove 'resizeMode="contain"' from the element, now the original problem only remains.

**Comment by sunkibaek** [comment]
Can it be `{user.name}` being undefined in some cases?

**Comment by bvanleeuwen1995** [comment]
I have just checked my DB and it is set for every record, so it should get the record.

Will check if the code might be the problem later today, since I'm currently working on a different project and don't have the time to check this for you.

**Comment by bvanleeuwen1995** [comment]
I have just checked, and user.name is always defined and has a value, so does user.photoUrl.

**Comment by bvanleeuwen1995** [comment]
I have just tried to build with the given example project linked in this repo, and it gives the same error as I'm having.

I'm using the latest xcode and iOS versions.

**Comment by kid-wumeng** [comment]
+1

**Comment by sunkibaek** [comment]
Will take a look at it soon. Thanks for the report!

**Comment by bvanleeuwen1995** [comment]
Thank you, do you have any time frame when this will be done?

That way I know if I will make a temp solution for the problem and implement this plugin later, this plugin is exactly what we need.

**Comment by sunkibaek** [comment]
I am not certain, but maybe I can get back to you within 24 hours.

By the way, it seems like the problem is with recent changes to the code base -- so if you want you can try the earlier version like `1.4.9` or `1.4.8`.

**Comment by bvanleeuwen1995** [comment]
Thank you for the information, i can confirm that using version 1.4.9 does not have this problem.
