### ISSUE TITLE
Indicator still present when prop omitted

### ISSUE THREAD

**Issue by sbardian** [huiseoul/react-native-fit-image#62]
When not including `indicator` prop on a FitImage component, there is still an indicator present.  I would expect no indicator if I do not include the `indicator` prop.  Currently you have to pass the `indicator` prop with a value of `false` to disable the indicator (which does not match the examples).

**Comment by sunkibaek** [comment]
I think the intention is to have `true` for indicator by default. So it will display indicator unless you explicitly set it to false. Sorry if there was confusion in the doc.
