### ISSUE TITLE
resizeMode=contain option triggers continuous reloading of image

### ISSUE THREAD

**Issue by srameshr** [huiseoul/react-native-fit-image#64]
When ```FitImage``` is used as the child of [ViewShot](https://github.com/gre/react-native-view-shot) with ```resizeMode="contain"``` option, it triggers continuous refresh.

Here is a basic reproducible demo:
```
<ViewShot ref="viewShot">
          <FitImage
            resizeMode="contain"
            source={this.state.image}
          />
</ViewShot>
```

**Comment by gre** [comment]
I don't think this is related to ViewShot at all?

![u](https://user-images.githubusercontent.com/211411/29739918-7914808e-8a4a-11e7-8619-057c34df01a2.gif)

```
├── react@16.0.0-alpha.12
├── react-native@0.47.2
└── react-native-fit-image@1.5.2
```
