### ISSUE TITLE
About LICENSE file...

### ISSUE THREAD

**Issue by fernando-sendMail** [huiseoul/react-native-fit-image#66]
Hey there!

This might an unpopular request for improvement, currently the project falls between 2 licenses.
The first one being ISC in the `package.json` file, and the other one being the Beerware 42 license.
Because of legal reasons we would like to have a more concrete defined license like ISC. I'm not a fan of legalities, but we need to have only one license for this package.

Please let me know your thoughts and let me know if I could help with anything.

**Comment by originerd** [comment]
https://github.com/huiseoul/react-native-fit-image/commit/9d7bea769379554e366b07d14eed2de1caa6719e

👍
