### ISSUE TITLE
Feature Request: Fit image radio with "fixed width" and "dynamic height"

### ISSUE THREAD

**Issue by wspl** [huiseoul/react-native-fit-image#75]
For example:

Network picture URL_A with size `{ height: 100, width: 200 }`
```jsx
<FitImage source={{uri: URL_A}} fixedWidth="500">
```
When network picture is fetched, FitImage view will resize automatically to  `{height: 250, width: 500}`

This feature would be very useful! Hope that anyone can implement this feature, thanks.

**Comment by sunkibaek** [comment]
@wspl 

Noted. Will add to feature roadmap. Thanks!
