### ISSUE TITLE
Some props are not working

### ISSUE THREAD

**Issue by hannigand** [huiseoul/react-native-fit-image#76]
Thanks for providing a great library. 

Quite a few Image PropTypes are not working with the component e.g. `onError`.

Similarly, could supported be added for the following props:

- onLayout
- onLoad
- onLoadStart

The component uses its own implementation of the above three, but I too need to provide my own implementation.

```javascript
<ImageComponent
  {...this.props}
  onLayout={this.onLayout}
  onLoad={this.onLoad}
  onLoadStart={this.onLoadStart}
  ...
>
```

This can be easily achieved by implementing the `onLayout` callback like so:

```javascript
// Pass event object as param
private onLoadStart = (e) => {
  if (this.isFirstLoad) {
    this.setState({ isLoading: true });
    this.isFirstLoad = false;
  }
  this.props.onLoadStart(e); // Added
}
```

**Comment by sunkibaek** [comment]
@hannigand 

That's good feedback. Although some callbacks are implemented the way you described, not all of them are. Will add this to feature roadmap.

Thanks!
