### ISSUE TITLE
undefined is not an object (evaluating '_react.PropTypes.bool')

### ISSUE THREAD

**Issue by giacomomasseron** [huiseoul/react-native-fit-image#80]
Hi,  
I updated react-native to 0.55 and I get this error:

undefined is not an object (evaluating '_react.PropTypes.bool')

when I import this package.  
Any idea to how to solve this?

**Comment by sunkibaek** [comment]
Sounds like `prop-types` are not installed for some reason. Can you verify you have prop-types under `/node-modules` ?

**Comment by giacomomasseron** [comment]
I solved, it was a typo error. Thanks.
