### ISSUE TITLE
Why does not borderRadius work?

### ISSUE THREAD

**Issue by gHashTag** [huiseoul/react-native-fit-image#82]
Why does not borderRadius work?

"react-native-fit-image": ^1.5.4,
"react": "16.4.1",
"react-native": "0.56.0",

```
fitImage: {
    borderRadius: 20,
}
...
<FitImage
  source={{ uri: 'https://facebook.github.io/react/img/logo_og.png' }}
  style={styles.fitImage}
/>
```

**Comment by sunkibaek** [comment]
@gHashTag Are you still experiencing this? It seems to work from my end.

**Comment by maxweb4u** [comment]
@gHashTag  It's not working, because ImageBackground doesn't support borderRadius :(

**Comment by sunkibaek** [comment]
Will close this issue--let me know if it persists.

**Comment by Li357** [comment]
Use the `imageStyle` prop which is spread to ImageBackground. TS throws an error since the props for FitImage extend ImageProps, not ImageBackgroundProps. Possible fix?

**Comment by shubhamchepe** [comment]
border radius does not work
