### ISSUE TITLE
We need feature to identify onError if the image url returns error

### ISSUE THREAD

**Issue by ManigandanRaamanathan** [huiseoul/react-native-fit-image#86]
We need feature to identify onError property if the image url returns error

**Comment by sunkibaek** [comment]
@ManigandanRaamanathan

If `onError` prop is added to the underlying `<Image />` component, will it solve the issue?

**Comment by sunkibaek** [comment]
Solved in https://github.com/huiseoul/react-native-fit-image/pull/99
