### ISSUE TITLE
npm publish?

### ISSUE THREAD

**Issue by iamacup** [huiseoul/react-native-fit-image#96]
hey @sunkibaek any chance of an NPM publish? or any timeline on when it might be? 

We depend on this at https://github.com/iamacup/react-native-markdown-display and could really use https://github.com/huiseoul/react-native-fit-image/pull/89 on NPM.

**Comment by sunkibaek** [comment]
@originerd has permission to do so but hard to reach this moment.

Let me keep trying to contact him.

**Comment by sunkibaek** [comment]
@iamacup Just released v1.5.5

Thanks!

**Comment by iamacup** [comment]
thanks @sunkibaek super appreciate it!
